NGmerge_flags: -m 10
RCA_batch_size: 10000
RCA_consensus_maximum: 20
RCA_consensus_minimum: 3
UMI_consensus_maximum: 1
UMI_consensus_minimum: 1
UMI_medaka_batches: 1
UMI_mismatches: 2
alignment_minimap2_flags: -a -A2 -B4 -O4 -E2 --end-bonus=30 --secondary=no
alignment_samtools_flags: ''
analyze_seqs_with_indels: true
colormap: kbc_r
consensusCopyDict:
  TrpB: TrpB
dashboard_input: TrpB
dashboard_port: 3366
demux_screen_failures: true
demux_screen_no_group: true
demux_threshold: 0.01
distribution_x_range: false
distribution_y_range: false
do_AA_mutation_analysis:
  TrpB: true
do_NT_mutation_analysis:
  TrpB: true
do_RCA_consensus:
  TrpB: true
do_UMI_analysis:
  TrpB: true
do_demux:
  TrpB: true
do_enrichment_analysis:
  TrpB: true
enrichment_SE_filter: 0
enrichment_missing_replicates_filter: true
enrichment_reference_bc: all_barcodes
enrichment_score_filter: false
enrichment_t0_filter: 0
export_SVG: false
fastq_dir: fastq_pass, fastq_fail
genotype_ID_alignments: 0
genotypes2D_plot_AA: true
genotypes2D_plot_all: false
genotypes2D_plot_downsample: 10000
genotypes2D_plot_groups: false
genotypes2D_plot_point_size_col: count
genotypes2D_plot_point_size_range: 30, 60
hamming_distance_distribution_downsample: 1000
hamming_distance_distribution_raw: false
highest_abundance_genotypes: 10
medaka_flags: --quiet
medaka_model: r104_e81_sup_variant_g610
memory:
  minimap2:
  - 8000
  - 500
merge_paired_end: false
metadata: metadata
mutation_analysis_quality_score_minimum: 5
mutations_frequencies_heatmap: true
mutations_frequencies_number_of_positions: 20
mutations_frequencies_raw: false
nanoplot: false
nanoplot_flags: --plots dot
peak_finder_settings: 40,3,9,2
plot_demux: true
plot_genotypes2D: false
plot_hamming-distance-distribution: true
plot_mutation-distribution: true
plot_mutation-distribution-violin: true
plot_mutation-frequencies: true
runs:
  TrpB:
    UMI_contexts:
    - GGNNNYRNNNYRNNNYRNNN
    - NNNYRNNNYRNNNYRNNNCA
    barcode_info:
      fwd:
        context: TNNNNNNN
        fasta: metadata/7merBarcodes.fasta
        generate: false
        hamming_distance: 0
        label_only: false
        reverse_complement: true
      lineage:
        context: NNNNNNNNNNNN
        fasta: metadata/lineageBarcodes.fasta
        generate: 100
        hamming_distance: 0
        label_only: true
        reverse_complement: false
      rvs:
        context: GCNNNNNNN
        fasta: metadata/7merBarcodes.fasta
        generate: false
        hamming_distance: 0
        label_only: false
        reverse_complement: false
    barcode_info_csv: metadata/barcode_info.csv
    partition_barcode_groups_csv: metadata/barcode_groups.csv
    reference: metadata/TrpB-ref.fasta
    reference_aln: metadata/.TrpB-ref_aln.fasta
    runname:
    - 20220827_1323_MN35267_FAU75463_1d527443
    splint: cggagtcaattaggtcatacNNNYRNNNYRNNNYRNNNCACTCGCACTGACTCGATNNNNNNNCGTCTTTCTGAGACCAGGAGGTCTCAAGGACTGCNNNNNNNCGTGTAGAGACTGCGTAGGNNNYRNNNYRNNNYRNNNgatgacctatacataggaagatctatag
sequence_length_threshold: 0.1
sequences_dir: data
threads_alignment: 4
threads_demux: 4
threads_medaka: 2
threads_samtools: 1
timepoints: metadata/timepoints.csv
timepointsInfo:
  TrpB-IE5:
    reference: metadata/TrpB-ref.fasta
    tag: TrpB
    tag_barcode_tp:
      ? !!python/tuple
      - TrpB
      - P1
      : '50'
      ? !!python/tuple
      - TrpB
      - P11
      : '150'
      ? !!python/tuple
      - TrpB
      - P13
      : '170'
      ? !!python/tuple
      - TrpB
      - P15
      : '190'
      ? !!python/tuple
      - TrpB
      - P17
      : '210'
      ? !!python/tuple
      - TrpB
      - P19
      : '230'
      ? !!python/tuple
      - TrpB
      - P3
      : '70'
      ? !!python/tuple
      - TrpB
      - P5
      : '90'
      ? !!python/tuple
      - TrpB
      - P7
      : '110'
      ? !!python/tuple
      - TrpB
      - P9
      : '130'
    units: generation
unique_genotypes_count_threshold: 5
uniques_only: false
version:
  full-tag: v0.10.4-29-gde897ea
  tag: development
